// NOVA Life OS — Demo Data for Alex (Founder / Creator)

import type { NovaState } from './types';
import { normalizeLoadedState } from './lib/sanitize';

const now = new Date().toISOString();
const today = new Date();
const daysAgo = (n: number) => new Date(today.getTime() - n * 86400000).toISOString();
const daysAhead = (n: number) => new Date(today.getTime() + n * 86400000).toISOString();

const rawState: Partial<NovaState> = {
  version: 3,
  goals: [
    {
      id: 'g1', title: 'Launch NOVA v1.0 publicly', description: 'Ship the first public release',
      category: 'Product', why: 'Build something that genuinely helps people manage their lives',
      status: 'active', priority: 'critical', deadline: daysAhead(45), progress: 65,
      milestones: [
        { id: 'm1', title: 'Complete all core screens', done: true },
        { id: 'm2', title: 'AI integration working', done: true },
        { id: 'm3', title: 'Beta test with 10 users', done: false },
        { id: 'm4', title: 'Performance optimization', done: false },
        { id: 'm5', title: 'Public launch', done: false },
      ],
      metrics: ['User retention > 60%', 'Life score avg > 65', 'Sub 2s load time'],
      obstacles: ['Scope creep', 'AI API costs', 'Time constraints'],
      relatedProjects: ['p1'], relatedHabits: ['h1', 'h2'], relatedTasks: ['t1', 't2'],
      createdAt: daysAgo(30), updatedAt: now, archived: false,
    },
    {
      id: 'g2', title: 'Reach $10k MRR', description: 'Monetize NOVA through subscriptions',
      category: 'Business', why: 'Financial independence and mission sustainability',
      status: 'active', priority: 'high', deadline: daysAhead(120), progress: 15,
      milestones: [
        { id: 'm6', title: 'First paying customer', done: true },
        { id: 'm7', title: '$1k MRR', done: false },
        { id: 'm8', title: '$5k MRR', done: false },
        { id: 'm9', title: '$10k MRR', done: false },
      ],
      metrics: ['MRR', 'Churn rate', 'LTV'],
      obstacles: ['Marketing budget', 'Pricing strategy'],
      relatedProjects: ['p2'], relatedHabits: [], relatedTasks: [],
      createdAt: daysAgo(20), updatedAt: now, archived: false,
    },
    {
      id: 'g3', title: 'Improve physical health', description: 'Build sustainable health habits',
      category: 'Health', why: 'Energy is the foundation of everything I do',
      status: 'active', priority: 'medium', deadline: null, progress: 40,
      milestones: [
        { id: 'm10', title: 'Walk daily for 30 days', done: false },
        { id: 'm11', title: 'Sleep 7h consistently', done: true },
        { id: 'm12', title: 'No caffeine after 2pm for 14 days', done: false },
      ],
      metrics: ['Daily steps > 8k', '7h sleep', 'Energy score > 70'],
      obstacles: ['Late night coding', 'Sedentary work'],
      relatedProjects: [], relatedHabits: ['h3', 'h4'], relatedTasks: [],
      createdAt: daysAgo(60), updatedAt: now, archived: false,
    },
  ],
  projects: [
    {
      id: 'p1', title: 'NOVA Life OS', description: 'Personal operating system',
      purpose: 'Make people\'s lives more organized and purposeful',
      why: 'The world needs tools that think like we do',
      category: 'Product', status: 'active', priority: 'critical',
      deadline: daysAhead(45), progress: 65,
      stages: ['Design', 'MVP', 'Beta', 'Launch'],
      tasks: ['t1', 't2', 't3'],
      roadmap: ['AI integration', 'Mobile app', 'Team features'],
      risks: ['Technical debt', 'Scope creep'],
      resources: ['https://github.com/nova-os'],
      relatedGoals: ['g1'],
      relatedIdeas: ['Zapier integration', 'iOS widget', 'Team workspace'],
      history: ['Started MVP', 'Added AI Chief', 'Launched marketplace'],
      aiRecommendations: [],
      createdAt: daysAgo(45), updatedAt: now, archived: false,
    },
    {
      id: 'p2', title: 'NOVA Marketing Site', description: 'Landing page and acquisition funnel',
      purpose: 'Drive signups for NOVA',
      why: 'Need users to validate the product',
      category: 'Marketing', status: 'active', priority: 'high',
      deadline: daysAhead(21), progress: 30,
      stages: ['Copy', 'Design', 'Dev', 'Launch'],
      tasks: [],
      roadmap: ['Landing page', 'Pricing page', 'Blog'],
      risks: ['Conversion rate unknown'],
      resources: [],
      relatedGoals: ['g2'],
      relatedIdeas: ['SEO content', 'Product Hunt launch'],
      history: [],
      aiRecommendations: [],
      createdAt: daysAgo(10), updatedAt: now, archived: false,
    },
  ],
  tasks: [
    {
      id: 't1', title: 'Build AI pattern detection engine', description: 'Analyze user behavior patterns',
      status: 'done', priority: 'critical', deadline: daysAgo(1),
      estimatedMinutes: 120, actualMinutes: 95, energyLevel: 'high',
      projectId: 'p1', goalId: 'g1', tags: ['ai', 'core'],
      createdAt: daysAgo(5), updatedAt: now, completedAt: daysAgo(1), archived: false,
      recurring: 'none', parentTaskId: null,
    },
    {
      id: 't2', title: 'Fix Finance budget save bug', description: 'updateSettings patch not saving monthlyBudget',
      status: 'done', priority: 'critical', deadline: now,
      estimatedMinutes: 30, actualMinutes: 25, energyLevel: 'high',
      projectId: 'p1', goalId: 'g1', tags: ['bug', 'finance'],
      createdAt: daysAgo(2), updatedAt: now, completedAt: now, archived: false,
      recurring: 'none', parentTaskId: null,
    },
    {
      id: 't3', title: 'Write launch blog post', description: 'Explain the vision for NOVA',
      status: 'todo', priority: 'high', deadline: daysAhead(7),
      estimatedMinutes: 90, actualMinutes: 0, energyLevel: 'medium',
      projectId: 'p2', goalId: 'g2', tags: ['content', 'marketing'],
      createdAt: daysAgo(3), updatedAt: now, completedAt: null, archived: false,
      recurring: 'none', parentTaskId: null,
    },
    {
      id: 't4', title: 'Beta outreach to 10 users', description: 'DM potential beta users',
      status: 'in_progress', priority: 'high', deadline: daysAhead(5),
      estimatedMinutes: 60, actualMinutes: 20, energyLevel: 'medium',
      projectId: 'p1', goalId: 'g1', tags: ['outreach'],
      createdAt: daysAgo(1), updatedAt: now, completedAt: null, archived: false,
      recurring: 'none', parentTaskId: null,
    },
    {
      id: 't5', title: 'Review subscription pricing', description: 'Research competitor pricing',
      status: 'todo', priority: 'medium', deadline: daysAhead(10),
      estimatedMinutes: 45, actualMinutes: 0, energyLevel: 'low',
      projectId: 'p2', goalId: 'g2', tags: ['business'],
      createdAt: daysAgo(1), updatedAt: now, completedAt: null, archived: false,
      recurring: 'none', parentTaskId: null,
    },
    {
      id: 't6', title: 'Morning 20-minute walk', description: 'Movement before screens',
      status: 'todo', priority: 'high', deadline: now,
      estimatedMinutes: 20, actualMinutes: 0, energyLevel: 'low',
      projectId: null, goalId: 'g3', tags: ['health'],
      createdAt: daysAgo(0), updatedAt: now, completedAt: null, archived: false,
      recurring: 'daily', parentTaskId: null,
    },
  ],
  habits: [
    {
      id: 'h1', title: 'Deep work session (2h)', description: 'Uninterrupted focused work block',
      category: 'Productivity', why: 'This is where the real work happens',
      frequency: 'daily', target: 1, streak: 5, bestStreak: 14,
      history: [daysAgo(0), daysAgo(1), daysAgo(2), daysAgo(3), daysAgo(4)],
      completionRate: 71, relatedGoalId: 'g1', isBad: false, stackedAfter: null,
      createdAt: daysAgo(21), updatedAt: now, archived: false,
    },
    {
      id: 'h2', title: 'Ship something every day', description: 'One deployable thing daily',
      category: 'Productivity', why: 'Compound momentum',
      frequency: 'daily', target: 1, streak: 3, bestStreak: 8,
      history: [daysAgo(0), daysAgo(1), daysAgo(2)],
      completionRate: 43, relatedGoalId: 'g1', isBad: false, stackedAfter: 'h1',
      createdAt: daysAgo(15), updatedAt: now, archived: false,
    },
    {
      id: 'h3', title: 'Morning walk (20 min)', description: 'Walk before any screens',
      category: 'Health', why: 'Clears my head and boosts energy for the day',
      frequency: 'daily', target: 1, streak: 2, bestStreak: 21,
      history: [daysAgo(0), daysAgo(1)],
      completionRate: 57, relatedGoalId: 'g3', isBad: false, stackedAfter: null,
      createdAt: daysAgo(30), updatedAt: now, archived: false,
    },
    {
      id: 'h4', title: 'No phone before 9am', description: 'Start with intention, not notifications',
      category: 'Health', why: 'My best creative ideas come before the internet',
      frequency: 'daily', target: 1, streak: 0, bestStreak: 5,
      history: [daysAgo(2), daysAgo(3), daysAgo(5)],
      completionRate: 43, relatedGoalId: 'g3', isBad: false, stackedAfter: null,
      createdAt: daysAgo(14), updatedAt: now, archived: false,
    },
    {
      id: 'h5', title: 'Doom scrolling', description: 'Mindless social media',
      category: 'Mindset', why: 'Tracking to break this pattern',
      frequency: 'daily', target: 0, streak: 0, bestStreak: 0,
      history: [daysAgo(0), daysAgo(1), daysAgo(2), daysAgo(3)],
      completionRate: 100, relatedGoalId: null, isBad: true, stackedAfter: null,
      createdAt: daysAgo(7), updatedAt: now, archived: false,
    },
  ],
  reflections: [
    {
      id: 'r1', date: daysAgo(0), text: 'Productive day. Shipped the pattern detection engine. Feeling momentum on NOVA. Some anxiety about the beta launch timeline but managing it.',
      mood: 7, energy: 8, stress: 4,
      tags: ['momentum', 'product', 'anxiety'],
      insights: ['Energy peaks when I ship things', 'Anxiety drops when I break big tasks into small ones'],
      linkedGoals: ['g1'], linkedTasks: ['t1'],
      createdAt: daysAgo(0),
    },
    {
      id: 'r2', date: daysAgo(1), text: 'Rough start — woke up with no energy. The no-phone habit broke. Afternoon recovered. Shipped the AI chat improvements.',
      mood: 5, energy: 4, stress: 6,
      tags: ['low-energy', 'recovery', 'habits'],
      insights: ['Phone in bed hurts next-day energy', 'Afternoon recovery is possible with a walk'],
      linkedGoals: ['g3'], linkedTasks: [],
      createdAt: daysAgo(1),
    },
    {
      id: 'r3', date: daysAgo(2), text: 'Best day in weeks. Deep work session hit 3 hours. Everything just clicked. Beta user feedback was really positive.',
      mood: 9, energy: 9, stress: 2,
      tags: ['peak-day', 'flow-state', 'feedback'],
      insights: ['Flow state happens when sleep > 7h + no morning phone', 'External validation shouldn\'t drive me but it does help'],
      linkedGoals: ['g1', 'g2'], linkedTasks: ['t4'],
      createdAt: daysAgo(2),
    },
    {
      id: 'r4', date: daysAgo(3), text: 'Scattered. Too many tabs open, literally and mentally. Tried to work on 3 things at once. Got none of them done.',
      mood: 4, energy: 5, stress: 7,
      tags: ['scattered', 'focus-fail', 'multitasking'],
      insights: ['Context switching is expensive', 'Need a hard rule: 1 task at a time'],
      linkedGoals: [], linkedTasks: [],
      createdAt: daysAgo(3),
    },
  ],
  finance: {
    transactions: [
      { id: 'f1', date: daysAgo(0), amount: 4200, type: 'income', category: 'Consulting', description: 'Monthly consulting retainer', tags: [], createdAt: daysAgo(0) },
      { id: 'f2', date: daysAgo(2), amount: 89, type: 'expense', category: 'Software', description: 'Vercel Pro', tags: ['tools'], createdAt: daysAgo(2) },
      { id: 'f3', date: daysAgo(3), amount: 320, type: 'expense', category: 'Food', description: 'Groceries + 3 restaurant meals', tags: [], createdAt: daysAgo(3) },
      { id: 'f4', date: daysAgo(4), amount: 150, type: 'expense', category: 'Transport', description: 'Uber rides + fuel', tags: [], createdAt: daysAgo(4) },
      { id: 'f5', date: daysAgo(5), amount: 99, type: 'expense', category: 'Software', description: 'OpenAI API credits', tags: ['ai', 'tools'], createdAt: daysAgo(5) },
      { id: 'f6', date: daysAgo(7), amount: 500, type: 'income', category: 'Freelance', description: 'Logo design project', tags: [], createdAt: daysAgo(7) },
      { id: 'f7', date: daysAgo(8), amount: 45, type: 'expense', category: 'Health', description: 'Gym membership', tags: ['health'], createdAt: daysAgo(8) },
    ],
    debts: [
      { id: 'd1', name: 'Student Loan', amount: 15000, remaining: 8400, interestRate: 4.5, minPayment: 320, repaymentSchedule: [], createdAt: daysAgo(730) },
    ],
    savingsGoals: [
      { id: 'sg1', title: 'Emergency Fund (3 months)', target: 12000, current: 7800, deadline: daysAhead(180), createdAt: daysAgo(180) },
      { id: 'sg2', title: 'Company Investment Fund', target: 50000, current: 3200, deadline: daysAhead(730), createdAt: daysAgo(60) },
    ],
    subscriptions: [
      { id: 'sub1', name: 'Figma', amount: 15, frequency: 'monthly', nextCharge: daysAhead(12), active: true, createdAt: daysAgo(365) },
      { id: 'sub2', name: 'Linear', amount: 8, frequency: 'monthly', nextCharge: daysAhead(18), active: true, createdAt: daysAgo(180) },
      { id: 'sub3', name: 'GitHub Copilot', amount: 10, frequency: 'monthly', nextCharge: daysAhead(5), active: true, createdAt: daysAgo(90) },
      { id: 'sub4', name: 'Notion', amount: 8, frequency: 'monthly', nextCharge: daysAhead(22), active: true, createdAt: daysAgo(400) },
    ],
    monthlyBudget: 2000,
  },
  contacts: [
    {
      id: 'c1', name: 'Maria Santos', relationship: 'Co-founder / Partner',
      birthday: daysAhead(45), phone: '+1234567890', telegram: '@mariasantos',
      notes: 'Brilliant. Call when stuck on strategy.',
      giftIdeas: ['Coffee subscription', 'Leadership book'],
      lastContactedAt: daysAgo(2), importance: 5,
      reminders: ['Monthly strategy call', 'Check on her product launch'],
      interactionLog: [
        { date: daysAgo(2), note: 'Video call — reviewed NOVA launch plan' },
        { date: daysAgo(9), note: 'Coffee — discussed pricing strategy' },
      ],
    },
    {
      id: 'c2', name: 'James Chen', relationship: 'Investor / Advisor',
      birthday: null, phone: '+9876543210', telegram: '',
      notes: 'Invested in 3 YC companies. Cold but very direct feedback.',
      giftIdeas: [],
      lastContactedAt: daysAgo(14), importance: 4,
      reminders: ['Monthly update email'],
      interactionLog: [
        { date: daysAgo(14), note: 'Email — sent monthly update' },
      ],
    },
    {
      id: 'c3', name: 'Mom', relationship: 'Family',
      birthday: daysAhead(90), phone: '+11112222333', telegram: '',
      notes: 'Call every Sunday.',
      giftIdeas: ['Flowers', 'Dinner out'],
      lastContactedAt: daysAgo(5), importance: 5,
      reminders: ['Sunday call', 'Birthday coming up in 3 months'],
      interactionLog: [
        { date: daysAgo(5), note: 'Phone call — Sunday check-in' },
      ],
    },
  ],
  skills: [
    {
      id: 'sk1', title: 'Deep Work', description: 'Ability to focus without distraction',
      category: 'Productivity', level: 4, xp: 75,
      prerequisites: [], practices: ['2h focus blocks', 'Phone-free sessions', 'Single-tab rule'],
      relatedHabits: ['h1'], relatedGoals: ['g1'],
      unlocks: ['Flow State Mastery', 'Creator Mode'],
    },
    {
      id: 'sk2', title: 'Product Strategy', description: 'Vision, roadmap, prioritization',
      category: 'Technical', level: 5, xp: 40,
      prerequisites: ['sk1'], practices: ['Weekly roadmap review', 'User interview', 'Competitor analysis'],
      relatedHabits: [], relatedGoals: ['g1', 'g2'],
      unlocks: ['Go-to-Market Mastery'],
    },
    {
      id: 'sk3', title: 'Financial Intelligence', description: 'Understanding money and investments',
      category: 'Mindset', level: 3, xp: 55,
      prerequisites: [], practices: ['Monthly audit', 'Read financial reports', 'Track all spending'],
      relatedHabits: [], relatedGoals: ['g2'],
      unlocks: ['Wealth Building'],
    },
    {
      id: 'sk4', title: 'Physical Endurance', description: 'Stamina and body resilience',
      category: 'Health', level: 2, xp: 30,
      prerequisites: [], practices: ['Daily walks', 'Cold showers', 'Consistent sleep'],
      relatedHabits: ['h3'], relatedGoals: ['g3'],
      unlocks: ['Peak Physical Performance'],
    },
  ],
  quests: [
    {
      id: 'q1', title: '30-Day Deep Work Challenge', description: 'Build the discipline of daily deep work',
      duration: 30, status: 'active', xpReward: 300,
      stages: [
        { title: 'Complete 7-day streak', done: true },
        { title: 'Reach 14 days', done: false },
        { title: 'Complete 30 days', done: false },
      ],
      dailyMissions: ['2h focus session', 'No social media during work', 'Evening review'],
      linkedGoal: 'g1', linkedHabits: ['h1'],
      boss: null, rewards: ['Deep Focus Badge', '300 XP', 'Skill unlock'],
      createdAt: daysAgo(7),
    },
    {
      id: 'q2', title: 'Financial Reset: 90 Days', description: 'Master your money and build savings habit',
      duration: 90, status: 'active', xpReward: 750,
      stages: [
        { title: 'Track all expenses for 30 days', done: true },
        { title: 'Build $1k emergency fund', done: false },
        { title: 'Cut 2 subscriptions', done: false },
        { title: 'Complete 90-day streak', done: false },
      ],
      dailyMissions: ['Log every expense', 'Review budget weekly', 'No impulse purchases'],
      linkedGoal: 'g2', linkedHabits: [],
      boss: 'b2', rewards: ['Financial Clarity Badge', '750 XP', 'CFO skill unlock'],
      createdAt: daysAgo(14),
    },
  ],
  bosses: [
    {
      id: 'b1', name: 'Procrastination Demon', description: 'Feeds on your excuses and delays',
      hp: 60, maxHp: 100, attacks: ['Distraction Storm', 'Doubt Spiral'],
      weakness: 'Small wins', linkedBadPattern: 'task_avoidance',
      victoryCondition: 'Complete 5 tasks in 2 days',
      rewards: ['100 XP', 'Task Slayer badge'],
      logs: [], defeated: false,
    },
    {
      id: 'b2', name: 'Debt Dragon', description: 'Grows when you ignore your finances',
      hp: 100, maxHp: 100, attacks: ['Interest Bite', 'Budget Drain'],
      weakness: 'Consistent tracking', linkedBadPattern: 'financial_avoidance',
      victoryCondition: 'Track expenses for 30 consecutive days',
      rewards: ['200 XP', 'Financial Clarity badge', 'CFO mentor unlock'],
      logs: [], defeated: false,
    },
    {
      id: 'b3', name: 'Burnout Hydra', description: 'Grows when you push too hard without recovery',
      hp: 80, maxHp: 80, attacks: ['Energy Drain', 'Focus Fog'],
      weakness: 'Recovery rituals', linkedBadPattern: 'overwork',
      victoryCondition: 'Maintain 7+ mood for 7 days',
      rewards: ['150 XP', 'Recovery Master badge'],
      logs: [], defeated: false,
    },
  ],
  mentors: [
    {
      id: 'men1', name: 'Marcus', persona: 'stoic_philosopher',
      tone: 'Direct and philosophical', domain: 'Life philosophy and resilience',
      rules: ['Never coddle', 'Always reference Stoic principles', 'Focus on what you control'],
      dataAccess: ['reflections', 'goals', 'tasks'],
      trustLevel: 3, unlockableQuotes: [
        'The impediment to action advances action. What stands in the way becomes the way.',
        'Waste no more time arguing about what a good man should be. Be one.',
      ],
    },
    {
      id: 'men2', name: 'Gordon', persona: 'cfo',
      tone: 'Blunt, numbers-focused', domain: 'Finance and business decisions',
      rules: ['Numbers only', 'No emotional decisions', 'Always ROI check'],
      dataAccess: ['finance', 'goals', 'projects'],
      trustLevel: 2, unlockableQuotes: [
        'Revenue solves most problems. What are you shipping today?',
      ],
    },
    {
      id: 'men3', name: 'Ava', persona: 'psychologist',
      tone: 'Curious, gentle, insightful', domain: 'Emotional intelligence and patterns',
      rules: ['Always ask why', 'Explore the root cause', 'Notice patterns across reflections'],
      dataAccess: ['reflections', 'habits', 'contacts'],
      trustLevel: 4, unlockableQuotes: [
        'The pattern you can see is the one you can break.',
      ],
    },
    {
      id: 'men4', name: 'Zero', persona: 'ruthless_operator',
      tone: 'No-nonsense, tactical', domain: 'Execution and results',
      rules: ['No excuses accepted', 'Results or reason', 'Action over analysis'],
      dataAccess: ['tasks', 'projects', 'goals'],
      trustLevel: 5, unlockableQuotes: [
        'Stop thinking. Start doing. Everything else is a story you\'re telling yourself.',
        'Ship. Ship again. Ship faster.',
      ],
    },
  ],
  protocols: [
    {
      id: 'pr1', name: 'Morning Launch', description: 'Start the day with maximum clarity and intention',
      category: 'Morning',
      steps: [
        'No phone for first 30 minutes',
        '5-minute NOVA daily brief review',
        'Set your #1 task for the day',
        'Write 3 things you\'re grateful for',
        'Start your first deep work block',
      ],
    },
    {
      id: 'pr2', name: 'Evening Shutdown', description: 'Close the day properly and protect tomorrow',
      category: 'Evening',
      steps: [
        'Complete NOVA evening review',
        'Mark all done tasks as complete',
        'Triage tomorrow\'s top 3 tasks',
        'Write a 2-sentence reflection',
        'Devices off by 10pm',
      ],
    },
    {
      id: 'pr3', name: 'Low Energy Day', description: 'When energy is low — protect it',
      category: 'Recovery',
      steps: [
        'Cancel non-essential meetings',
        'Do only 1 task (admin or low-effort)',
        '20-minute walk outside',
        'No caffeine after noon',
        'Sleep 1 hour earlier than usual',
      ],
    },
    {
      id: 'pr4', name: 'Spending Decision', description: 'Before any non-essential purchase > $50',
      category: 'Finance',
      steps: [
        'Wait 24 hours',
        'Check monthly budget remaining',
        'Ask: does this serve my goals?',
        'Find 1 alternative or DIY option',
        'If still yes after 24h — proceed',
      ],
    },
    {
      id: 'pr5', name: 'Founder Feature Decision', description: 'Before adding any new feature to NOVA',
      category: 'Product',
      steps: [
        'Write the user problem in 1 sentence',
        'Check if 3+ users have requested it',
        'Estimate implementation time',
        'Ask: does this serve the core mission?',
        'If yes to all 4 — add to roadmap',
      ],
    },
  ],
  aiMessages: [],
  settings: {
    theme: 'dark', accentColor: 'cyan', language: 'en', pinEnabled: false, pin: null,
    aiProvider: 'mock', privacyMode: false,
    dashboardCards: ['lifeScore', 'clarityScore', 'energyScore', 'progressScore', 'weeklyProgress', 'activeGoals', 'activeProjects', 'focusTime', 'habitsCompletion', 'financeOverview', 'reflectionTrend', 'upcomingDeadlines', 'aiInsight'],
    monthlyBudget: 2000,
    budgetCategories: [],
    weekStartsOn: 1,
    dailyReviewTime: '21:00',
  },
  todayMission: null,
  achievements: [],
  patternInsights: [],
  timeCapsules: [],
  profile: {
    name: 'Alex',
    role: 'Founder / Creator',
    avatar: '',
    level: 7,
    xp: 400,
    totalXpEarned: 3400,
    lifeScore: 72,
    clarityScore: 68,
    energyScore: 61,
    progressScore: 74,
    joinedAt: daysAgo(30),
    currentStreak: 5,
    longestStreak: 12,
    lastActiveDate: daysAgo(0),
  },
};

export function getDemoState(): NovaState {
  return normalizeLoadedState(rawState);
}
